# Generated by Django 4.0.6 on 2023-02-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='phone_number',
        ),
    ]
